# Generated by Django 5.0.7 on 2024-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('wallet', models.CharField(blank=True, max_length=150, unique=True)),
                ('dateTime', models.DateField(auto_now_add=True)),
                ('totalScore', models.PositiveIntegerField(default=0)),
                ('lastlogin', models.DateField(auto_now_add=True)),
                ('streak', models.IntegerField(default=0)),
            ],
        ),
    ]
