# Generated by Django 5.0.7 on 2024-08-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
