# Generated by Django 5.0.7 on 2024-08-14 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastlogin',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
