# Generated by Django 5.0.7 on 2024-08-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskEntry',
            new_name='TaskProgress',
        ),
    ]
