# Generated by Django 5.0.7 on 2024-08-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='fromUser',
            field=models.IntegerField(),
        ),
    ]
