# Generated by Django 5.0.7 on 2024-09-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_invites_amount_invites_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='withdrawRequest',
            field=models.BooleanField(default=False),
        ),
    ]
